shell/agents/AIShell.OpenAI.Agent/Agent.cs

Fixed small GTP Typo

---

README.md
docs/CODE_OF_CONDUCT.md
docs/SECURITY.md

Updates the readme, code of conduct and security policy per OSPO request.

Update Code of Conduct and Security Policy

---

.pipelines/Build-Official.yml
.pipelines/templates/linux.yml
.pipelines/templates/mac.yml
.pipelines/templates/sign-files.yml
.pipelines/templates/update-nuget-config.yml
.pipelines/templates/windows.yml
build.psm1
tools/Metadata.json
tools/metadata.json

Update the release build pipeline to make it work as expected. The build pipeline finally passed:
https://dev.azure.com/mscodehub/PowerShellCore/_build/results?buildId=523690&view=results

Update the release build pipeline to make it work as expected

---

.pipelines/Build-Official.yml
.pipelines/Package-Official.yml
.pipelines/templates/check-Azure-container.yml
.pipelines/templates/linux-package.yml
.pipelines/templates/mac-package.yml
.pipelines/templates/module-package.yml
.pipelines/templates/nupkg-package.yml
.pipelines/templates/upload-to-Azure.yml
.pipelines/templates/windows-package.yml
shell/AIShell.Integration/AIShell.Integration.csproj

Fix all the issues with the packaging pipeline. Now the packaging pipeline works as expected.

Fix all the issues with the packaging pipeline

---

shell/agents/Microsoft.Azure.Agent/ChatSession.cs
shell/agents/Microsoft.Azure.Agent/Schema.cs
shell/agents/Microsoft.Azure.Agent/Utils.cs

Improve diagnosis by including the activity JSON payload when the received activity is unexpected.

Improve diagnosis by including the activity JSON payload when it's unexpected

---

.pipelines/Package-Official.yml
build.psm1
shell/AIShell.Integration/AIShell.Integration.csproj
shell/shell.common.props

Update the module version according to the product version, so the version can be automatically updated during build.

Update the module version according to the product version

---

.pipelines/Build-Official.yml
.pipelines/Package-Official.yml
.pipelines/Release-Official.yml
.pipelines/templates/linux-build.yml
.pipelines/templates/mac-build.yml
.pipelines/templates/module-build.yml
.pipelines/templates/module-package.yml
.pipelines/templates/release-msix-bundle.yml
.pipelines/templates/release-publish-github.yml
.pipelines/templates/release-publish-module.yml
.pipelines/templates/release-publish-nuget.yml
.pipelines/templates/wait-for-approval.yml
.pipelines/templates/windows-build.yml

Initial check-in for the OneBranch release pipeline.
Changes have been verified with a build pipeline run and a package pipeline run:
https://dev.azure.com/mscodehub/PowerShellCore/_build/results?buildId=533391&view=results
https://dev.azure.com/mscodehub/PowerShellCore/_build/results?buildId=533452&view=results

Initial check-in for the OneBranch release pipeline

---

.pipelines/Release-Official.yml
.pipelines/templates/release-publish-github.yml
.pipelines/templates/release-publish-module.yml
.pipelines/templates/release-publish-nuget.yml

Fix all known issues with the release pipeline. Changes have been validated with OneBranch pipeline runs.

Fix all known issues with the release pipeline

---

README.md

Added privacy statement sharing we don't capture any PII for AIShell.
Want to ensure we are sharing the fact we are not capturing any personal data or PII with AIShell.

Updated README on privacy statement 

---

build.psm1

Fix the build script to not create a folder multiple times.

Fix build script to not create a folder multiple times

---

shell/AIShell.Integration/Commands/StartAishCommand.cs

Address #269
Fix `Start-AIShell` to correctly get the executable path from PATH env variable

Fix `Start-AIShell` to correctly get the executable path from PATH env variable

---

shell/AIShell.Kernel/Command/RefreshCommand.cs

Fix #270 -- Update the description of `/refresh`

Update the description of `/refresh`

---

README.md
docs/FAQ.md

Remove docs about `az-cli` and `az-ps` agents.

Remove docs about `az-cli` and `az-ps` agents

---

shell/agents/Microsoft.Azure.Agent/Telemetry.cs

After the PR being merged, we will need SAW to achieve the targeted Application Insights. And the data pipeline will need a priod of time (once per 1hr) to sync it to our prod Kusto Table.

Switch to app insights in AME (prod) Environment.

---

shell/agents/Microsoft.Azure.Agent/Utils.cs

Add telemetry when receiving corrupt data from Azure Copilot.

Add telemetry when receiving corrupt data from Azure Copilot

---

shell/agents/Microsoft.Azure.Agent/Command.cs

Fixing typo in placeholder replacement message

Fixed typo in Command.cs

---

README.md
docs/CONTRIBUTING.md
docs/FAQ.md
docs/SUPPORT.md
docs/development/CreatingAnAgent.md
shell/AIShell.Integration/AIShell.psd1
tools/packaging/packaging.strings.psd1

Since we are approved to use the name AI Shell, we are removing the Project Mercury codename from the repository. There still may need to be changes to the pipeline for the future release cc @daxian-dbw

Removing Project Mercury Codename from README and other documentation

---

.pipelines/Build-Official.yml
.pipelines/templates/linux-build.yml
.pipelines/templates/mac-build.yml
.pipelines/templates/module-build.yml
.pipelines/templates/module-package.yml
.pipelines/templates/nupkg-package.yml
.pipelines/templates/release-publish-github.yml
.pipelines/templates/windows-build.yml
.pipelines/templates/windows-package.yml
README.md

Update pipeline YAML files for repo name change.

Update pipeline YAML files for repo name change

---

.pipelines/templates/linux-package.yml

Missed a change in `linux-package.yml` for the repo renaming.

Change repo name in `linux-package.yml`

---

tools/scripts/install-aishell.ps1

Check PS version to be 7.4.6 or above before running the code. Otherwise newer syntax would fail in PS 5.1

add check for PS version before code run

---

.github/workflows/dotnet.yml

Update GitHub workflow with .NET 8.0.403

Update GitHub workflow with .NET 8.0.403

---

shell/AIShell.Kernel/Utility/ReadLineHelper.cs

Fix #238
Ignore the current active agent from the agent completion results for `@`.

Ignore the current active agent from the agent completion results for `@`
