PowerShell/AIShell

shell/AIShell.Kernel/Command/CommandRunner.cs
shell/AIShell.Kernel/Command/ReplaceCommand.cs
shell/AIShell.Kernel/Shell.cs
shell/AIShell.Kernel/Utility/ReadLineHelper.cs
shell/ReadLine/Cmdlets.cs
shell/ReadLine/Completion.cs
shell/ReadLine/Options.cs
shell/ReadLine/Prediction.Entry.cs
shell/ReadLine/Prediction.Views.cs
shell/ReadLine/Prediction.cs
shell/ReadLine/ReadLine.cs
shell/ReadLine/Render.cs

This PR is the preparation work to support the parameter injection scenario.
1. Update the prediction to support empty-string input, and enable prediction fresh into the `ReadLine` call, before user pressing any keystroke.
- Update `ForceRender` to be able to cancel rendering when it's okay to do so.
1. Update the list view to support smaller terminal width (`MinWindowWidth = 30`), and stop rendering the source part in list items when the terminal width is `< 50`.
1. Fix the prompt when user press <kbd>Ctrl+c</kbd> within `ReadLine` call.
1. Add the `/replace` to validate the changes for the parameter injection scenario. This command is temporary and will be replaced later.
- I will provide a utility API to assist the argument replacement, then an agent can decide if it want to expose a …

Enable empty input prediction and make list view support smaller width

---

docs/development/CreatingAnAgent.md

Small bug found in agents creation doc that makes the ollama one not build since we have changed shell_dir to agents_dir.

update readme to account for new agents folder

---

docs/development/CreatingAnAgent.md

after a recent update, the path is still erroring when using `agents_dir` but rather it should be `agent_dir` for the build script to complete. This PR updates the readme instructions to account for this.

update agents path on readme to fix path error

---

shell/AIShell.Kernel/Command/AgentCommand.cs
shell/AIShell.Kernel/LLMAgent.cs
shell/AIShell.Kernel/Shell.cs
shell/AIShell.Kernel/Utility/ReadLineHelper.cs

Fix #205
Support switching agent by tagging an agent's name:
1. Support `@<agent>` and `@<agent> <query>` to switch to a different agent, or switch and send the query to that agent.
- For `@<agent>` only, landing page of that agent will be display, just like running `/agent use <agent>`
- For `@<agent> <query>`, we assume the user already knows about the capabilities of the target agent and thus won't show the landing page of that agent again.
1. The prompt is updated to use the name of the current active agent by default. When `--shell-wrapper` is used at startup, the prompt defined in the `wrapper.json` will be used for the agent declared in the same file. 
1. When no agent is available, the default prompt `aish` will be used.
1. Tab completion and prediction for the `@<agent>` are …

Support switching agent by tagging an agent's name

---

shell/AIShell.Kernel/Utility/ReadLineHelper.cs
shell/ReadLine/PublicAPI.cs
shell/ReadLine/Render.cs

Support syntax highlighting for AIShell read-line experience:
1. For a command, the command name, parameter, argument are syntax highlighted
1. For tagging an agent, the '@' mention is highlighted

Support syntax highlighting for AIShell read-line experience

---

shell/AIShell.Kernel/Shell.cs
shell/AIShell.Kernel/Utility/ReadLineHelper.cs
shell/Markdown.VT/Render/Inlines/CodeInlineRenderer.cs

Per the discussion with Hiyo, change to
1. Use foreground default for markdown inline code.
2. Use green for AIShell command, both in text and in read-line syntax highlighting.

Update the color for markdown inline code and AIShell command

---

shell/agents/AIShell.Azure.Agent/AzCLI/AzCLISchema.cs
shell/agents/AIShell.Azure.Agent/AzCLI/Command.cs
shell/agents/AIShell.Azure.Agent/AzCLI/UserValueStore.cs

A few improvement to parameter injection
1. Do not include 'placeholderSet' in a history entry when its value is null.
2. Reduce the fake wait time when replacing user values from 2.5s to 2s.
3. Change the format for a pseudo value from `__replace_<cnt>_v__` to `__pseudo_<cnt>_v__` to avoid confusion caused to GPT by the word 'replace'.

A few improvement to parameter injection

---

shell/AIShell.Integration/Channel.cs

Make `Singleton` property and `StartChannelSetup()` method from the `AIShell.Integration.Channel` class public, so that a developer can utilize the API to create a pipe for an `aish` to collect to.

Make `Singleton` property and `StartChannelSetup()` method public

---

build.psm1
shell/AIShell.Abstraction/AIShell.Abstraction.csproj
shell/AIShell.Integration/AIShell.Integration.csproj
shell/agents/AIShell.Interpreter.Agent/AIShell.Interpreter.Agent.csproj
shell/agents/AIShell.Ollama.Agent/AIShell.Ollama.Agent.csproj
shell/agents/AIShell.OpenAI.Agent/AIShell.OpenAI.Agent.csproj
shell/nuget.config

The build was updated so that `AIShell.Integration` and `AIShell.*.Agent` are all depend on the project of `AIShell.Abstraction` instead of the NuGet package of it. In this way, we can get rid of the dependency of a local feed, which is causing CFS issue to this repo.

Update build to remove the dependency of a local feed

---

.config/tsaoptions.json
.pipelines/templates/linux-build.yml
.pipelines/templates/mac-build.yml
.pipelines/templates/module-build.yml

1. Update area path for AIShell
2. Update the build pipeline to build again or restore in the signing job, to generate the correct SBOM

Update area path and fix build to generate correct SBOM

---

build.psm1
shell/AIShell.Abstraction/UserAction.cs

A couple minor fixes:
1. The `Refresh` command calls the agent implementation directly, so there is no point to trigger a user action for it.
2. Add the `win-x86` RID to `Update-CFSFeed`.

A couple minor fixes

---

.github/workflows/dotnet.yml
shell/agents/AIShell.Azure.Agent/AIShell.Azure.Agent.csproj

Update the package `Microsoft.ApplicationInsights.WorkerService` to 2.22.0 to fix the CVE issue reported in ADO.

Update the package 'Microsoft.ApplicationInsights.WorkerService' to 2.22.0

---

shell/AIShell.Abstraction/ILLMAgent.cs
shell/AIShell.Kernel/Command/AgentCommand.cs
shell/AIShell.Kernel/Command/RefreshCommand.cs
shell/AIShell.Kernel/LLMAgent.cs
shell/AIShell.Kernel/Shell.cs
shell/agents/AIShell.Azure.Agent/AzCLI/AzCLIAgent.cs
shell/agents/AIShell.Azure.Agent/AzPS/AzPSAgent.cs
shell/agents/AIShell.Interpreter.Agent/Agent.cs
shell/agents/AIShell.Ollama.Agent/OllamaAgent.cs
shell/agents/AIShell.OpenAI.Agent/Agent.cs
shell/shell.common.props

The orchestrator approach I tried with those interfaces doesn't really orchestrate across agents, and it requires the user to run `/agent pop` to return to the orchestrator after done with an agent selected by the orchestrator. That just won't work.
If we're ever going to support an orchestrator, it should be something like the Azure Orchestrator, where the user only talk to the orchestrator without needing to know what is happening behind the orchestrator.
- This PR removes those interfaces and the related experimenting code, so as to make it easier to refactor the code base for new feature request.
- The `void RefreshChat()` method is changed to an async method `Task RefreshChatAsync(IShell shell)`. This will be the place where an agent reset chat states, interact with user for …

Remove the `IOrchestrator` and `ICodeAnalyzer` interfaces

---

shell/AIShell.Kernel/Shell.cs

Minor fix to the calls of 'WriteErrorLine'. Given that `WriteErrorLine(string)` will prepend the error message with the prefix `Error: `, we should not add `\n` in the beginning of the error message.

Minor fix to the calls of 'WriteErrorLine'

---

build.psm1
shell/AIShell.Abstraction/IHost.cs
shell/AIShell.Kernel/Host.cs
shell/agents/AIShell.Azure.Agent/AzCLI/Command.cs
shell/agents/Microsoft.Azure.Agent/AzureAgent.cs
shell/agents/Microsoft.Azure.Agent/AzureCopilotReceiver.cs
shell/agents/Microsoft.Azure.Agent/ChatSession.cs
shell/agents/Microsoft.Azure.Agent/Microsoft.Azure.Agent.csproj
shell/agents/Microsoft.Azure.Agent/Schema.cs
shell/agents/Microsoft.Azure.Agent/Utils.cs

Initial check-in for the new `azure` agent that talks to the Azure Orchestrator.
- Add the initial work of the new agent, which talks to Azure Copilot with token grabbed from Azure Portal manually.
- Wrap the client web socket into a data structure that allows us to easily consume both streaming and non-streaming output.
- Get it ready to support authentication in a more streamline way in `RefreshChatAsync`.

Initial check-in for the new `azure` agent that talks to the Azure Orchestrator

---

.pipelines/Build-Official.yml
.pipelines/Package-Official.yml
.pipelines/templates/check-Azure-container.yml
.pipelines/templates/module-package.yml

This PR is for resolve a CFS issue caused by `Register-PSResourceRepository` and `Publish-Module` from `PowerShellGet`. Those 2 cmdlets seem to talk to `nuget.org` even though we just want to register a local repository with a local folder path.
KS3 is not enforced for Windows in the packaging pipeline because it would block operations on the Azure container/blobs using Azure PowerShell cmdlet. The operations will fail after 6 re-tries:
> ##[error]Retry failed after 6 tries. Retry settings can be adjusted in ClientOptions.Retry or by configuring a custom retry policy in ClientOptions.RetryPolicy.
Test OneBranch build: https://dev.azure.com/mscodehub/PowerShellCore/_build/results?buildId=532130&view=results

Enforce KS3 for Linux agent and also use PSResourceGet command for creating `nupkg` for the `AIShell` module

---

shell/agents/Microsoft.Azure.Agent/AzureCopilotReceiver.cs
shell/agents/Microsoft.Azure.Agent/ChatSession.cs
shell/agents/Microsoft.Azure.Agent/Schema.cs

When error happens in the web socket receiver thread, we create a `CopilotActivity` with the exception from the error, and pass add it to the collection. When the agent reads from the receiver, if the next activity's `Error` field is not null, then the error gets thrown out at the consumer side.

Handle errors that may happen in the web socket receiver thread

---

shell/agents/Microsoft.Azure.Agent/AzureAgent.cs

Update the footer that indicates the turns of a conversation according to the UI design.
Now, instead of showing the footer for every response, we start to show it when there are 5 or less requests left for the current conversation.

Update the footer that indicates the turns of a conversation according to the UI design

---

shell/AIShell.Integration/Commands/InvokeAishCommand.cs
shell/AIShell.Integration/Commands/ResolveErrorCommand.cs
shell/AIShell.Integration/Commands/StartAishCommand.cs

Make the `-Query` parameter accept values from remaining arguments, so that a user doesn't have to always enclose a query in quotes. Instead, one can run `Invoke-AIShell what are the different types of functions?`

Invoke-AIShell: make the `-Query` parameter accept values from remaining arguments

---

shell/agents/Microsoft.Azure.Agent/AzureAgent.cs
shell/agents/Microsoft.Azure.Agent/ChatSession.cs
shell/agents/Microsoft.Azure.Agent/Command.cs
shell/agents/Microsoft.Azure.Agent/DataRetriever.cs

Simplify parameter injection UI and fix a few bugs.
- Stop showing the parameter description from the help cache.
- Stop showing the naming restrictions, and simplify the pattern recommendation.
- Use the command snippet as the caption with the short description generated by GPT.
- Fix the value replacement code to set `Updated` correctly
- Fix the placeholder-parameter pairing code to handle the case where a code block contains multiple `az` commands.

Simplify parameter injection UI and fix a few bugs

---

shell/AIShell.Integration/AIShell.Integration.csproj
shell/agents/Microsoft.Azure.Agent/AzureAgent.cs

Use more concise spinner for 'Azure' agent because the status update message from Azure Copilot could be long.

Use more concise spinner for 'Azure' agent

---

shell/agents/Microsoft.Azure.Agent/AzureAgent.cs
shell/agents/Microsoft.Azure.Agent/ChatSession.cs
shell/agents/Microsoft.Azure.Agent/DataRetriever.cs
shell/agents/Microsoft.Azure.Agent/Schema.cs
shell/agents/Microsoft.Azure.Agent/Utils.cs

Move away from the local cache files to the Az CLI metadata service
- Use a single `HttpClient` instance for all requests sent from the `Azure` agent.
- Replace the local cache files with the AzCLI metadata service for static argument values.
- the timeout for querying the metadata service is set to 1.2 seconds
- proceed to Az CLI tab completion for dynamic values only if the parameter has completer or if the metadata for the parameter is unavailable

Move away from the local cache files to the Az CLI metadata service

---

shell/agents/Microsoft.Azure.Agent/AzureAgent.cs
shell/agents/Microsoft.Azure.Agent/AzureCopilotReceiver.cs
shell/agents/Microsoft.Azure.Agent/ChatSession.cs
shell/agents/Microsoft.Azure.Agent/DataRetriever.cs
shell/agents/Microsoft.Azure.Agent/Microsoft.Azure.Agent.csproj

Add basic logging for error cases in the Azure agent.
- Use `Serilog` as it supports file logging. I considered `Microsoft.Extension.Logging` which has built-in logging provider for Event Source, but decided to not use it because it's easier to share a file log for diagnosis purposes.
- The logging is configured to be rolling over by day, and it uses async writing to the log file.
- The logging enabled so far is error only, but we can add more information/debug loggings for better view of the code operation.
- We will need to allow a user to disable logging in the agent's configuration file. **This is not done in this PR.**

Add basic logging for error cases in the Azure agent

---

shell/agents/Microsoft.Azure.Agent/AzureAgent.cs
shell/agents/Microsoft.Azure.Agent/ChatSession.cs
shell/agents/Microsoft.Azure.Agent/Schema.cs

Expose more states to prepare for telemetry collection
- `CopilotResponse` received from a chat is now saved in a private member of the agent, so its states could be used by telemetry.
- Offer the `ConversationId` property in `ChatSession` for getting the current conversation id.
- Expose `ReplyToId` in `CopilotResponse`, which is the activity id of the user's query that the current response replies to.

Expose more states to prepare for telemetry collection

---

shell/agents/Microsoft.Azure.Agent/AzureAgent.cs
shell/agents/Microsoft.Azure.Agent/AzureCopilotReceiver.cs
shell/agents/Microsoft.Azure.Agent/ChatSession.cs
shell/agents/Microsoft.Azure.Agent/DataRetriever.cs
shell/agents/Microsoft.Azure.Agent/Schema.cs

Add some more logging entries and support agent settings
- Add a few more logging entries at the `Debug` level
- Add support for the agent setting, initially with 2 properties only: `logging` and `telemetry`, both are boolean values.
- By default, `logging` and `telemetry` are both `true`, meaning both are enabled.
- A new config file will be created if it doesn't exist, and the default values will be used.

Add some more logging entries and support agent settings

---

shell/AIShell.Abstraction/ILLMAgent.cs
shell/AIShell.Kernel/Command/RefreshCommand.cs
shell/AIShell.Kernel/Shell.cs
shell/agents/AIShell.Azure.Agent/AzCLI/AzCLIAgent.cs
shell/agents/AIShell.Azure.Agent/AzPS/AzPSAgent.cs
shell/agents/AIShell.Interpreter.Agent/Agent.cs
shell/agents/AIShell.Ollama.Agent/OllamaAgent.cs
shell/agents/AIShell.OpenAI.Agent/Agent.cs
shell/agents/Microsoft.Azure.Agent/AzureAgent.cs
shell/agents/Microsoft.Azure.Agent/ChatSession.cs
shell/agents/Microsoft.Azure.Agent/Command.cs
shell/agents/Microsoft.Azure.Agent/Schema.cs
shell/shell.common.props

Add authentication to the `Azure` agent.
- Generate DL token using the new "conversation start" API
- Refresh token potentially before each query
- Update the interface method `RefreshChatAsync` to take another parameter `bool force`, to indicate whether or not to force creating a new chat session. Only `/refresh` command will call this method with `force = true`, because that's an explicit action from user to refresh the current chat session. In other cases, it's up to the agent to decide how it want to do the refreshing, for example, refreshing the token only, or reload the setting.
- This change is required by the `Azure` agent. A user only gets fixed number of chat sessions per day, so we don't want to keep creating new chat sessions when user is simply switching agents.
- For a soft …

Add authentication to the `Azure` agent

---

shell/AIShell.Abstraction/ILLMAgent.cs
shell/AIShell.Kernel/LLMAgent.cs
shell/AIShell.Kernel/Shell.cs
shell/agents/AIShell.Interpreter.Agent/Agent.cs
shell/agents/AIShell.OpenAI.Agent/Agent.cs
shell/agents/Microsoft.Azure.Agent/AzureAgent.cs
shell/agents/Microsoft.Azure.Agent/ChatSession.cs
shell/agents/Microsoft.Azure.Agent/Command.cs

Multiple fixes and UI improvements based on feedback
1. Fix a bug when run `@Azure <query>` before the `Azure` agent starts a chat session.
2. Reset argument placeholder information when `RefreshChatAsync` is called on the `Azure` agent.
3. Update the initial agent selection message to let the user know they can switch to another agent later by `@` tagging its name.
4. Update the read-line prompt to start with `@`, like `@Azure> `, so as to make the `@` tagging more obvious.
5. Update the color used for `/replace` in the `Run /replace to get assistance in placeholder replacement` message to be more eye catching.

Multiple fixes and UI improvements based on feedback

---

shell/agents/Microsoft.Azure.Agent/AzureAgent.cs

- Reset the `_turnLeft` field of the `azure` agent when a new chat session is created.
- Rename the agent to be `azure`

Reset the `_turnLeft` field of the `azure` agent when a new chat session is created

---

shell/agents/Microsoft.Azure.Agent/AzureAgent.cs
shell/agents/Microsoft.Azure.Agent/ChatSession.cs
shell/agents/Microsoft.Azure.Agent/Schema.cs

- Handle error message from the Azure Orchestrator.
- Add `ConversationId` property to the `CopilotResponse` type.
The Azure Orchestrator may return an error message like this:
```json
{
"type": "message",
"id": "7zoAgmG58OPJttpKKYnYqZ-us|0000002",
"timestamp": "2024-10-28T17:59:41.5245466Z",
"channelId": "directline",
"from": {
"id": "copilotweb-canary-prod",
"name": "copilotweb-canary-prod"
},
"topicName": "Orchestrator",
"text": "Sorry, Copilot encountered an error. Please try again or share your feedback.\nActivityId = 7zoAgmG58OPJttpKKYnYqZ-us|0000001, CorrelationID = 7zoAgmG58OPJttpKKYnYqZ-us|0000001, Timestamp = 2024-10-28T17:59:41.4950709Z",
"inputHint": "error",
"locale": "en-US",
"attachments": [
{
"contentType": "azurecopilot/conversationstate",
"content": {
"turnLimit": 15, …
```

Handle error message from the Azure Orchestrator

---

build.psm1
shell/AIShell.Integration/AIShell.psd1

Move from in-box help content to updateable help.

Move from in-box help content to updateable help

---

shell/agents/Microsoft.Azure.Agent/AzureAgent.cs
shell/agents/Microsoft.Azure.Agent/ChatSession.cs
shell/agents/Microsoft.Azure.Agent/Schema.cs
shell/agents/Microsoft.Azure.Agent/Utils.cs

Refactored the authentication flow and add the check for Copilot access.
- Encapsulated the token life cycle management into separate classes `UserAccessToken` and `UserDirectLineToken`. The health of the token is tracked within those types, which expose the renew method.
- This is a preparation for using the `pluginstore` feature flag, which requires the client to send user access token along with every request, and that means we need to keep 2 tokens alive.
- Refactored the authentication flow using the new encapsulated tokens.
- Add the step to check if the user has Copilot access.

Refactored the authentication flow and add the check for Copilot access

---

shell/agents/Microsoft.Azure.Agent/AzureAgent.cs
shell/agents/Microsoft.Azure.Agent/Telemetry.cs

- Updated Installation Id Initialization to support both AzPS and AzCLI on Unbuntu. Tested on both ubuntu dockers for azps and azcli.
- AzCLI:
- ![image](https://github.com/user-attachments/assets/44d21a8a-e73d-4f2a-ad1b-a478350a6598)
- AzPSH:
- ![image](https://github.com/user-attachments/assets/beab59be-9fac-4f64-90e1-2d6dc7696e9d)

Update the telemetry for msaz

---

shell/agents/Microsoft.Azure.Agent/ChatSession.cs
shell/agents/Microsoft.Azure.Agent/Utils.cs

- Change to the `canary` Copilot Access endpoint because the production endpoint doesn't work in some regions.
- Update `EnsureSuccessStatusCodeForTokenRequest` to use `"<empty>"` when the response message is null or empty.

Change to the `canary` Copilot Access endpoint because the production endpoint doesn't work in some regions

---

shell/agents/Microsoft.Azure.Agent/AzureAgent.cs
shell/agents/Microsoft.Azure.Agent/ChatSession.cs
shell/agents/Microsoft.Azure.Agent/Telemetry.cs

Remove ids for correlation from telemtry except the situation when users give feedback.

---

shell/agents/Microsoft.Azure.Agent/DataRetriever.cs

Skip retrieving dynamic argument values on non-Windows platforms.
Also added `GetAzCLIPythonPath()` to calculate the right AzCLI python path for different platforms and installations.

Skip retrieving dynamic argument values on non-Windows platforms

---

shell/agents/Microsoft.Azure.Agent/Telemetry.cs

This PR did:
- Remove id for correlation from Exception. Although The `Exception` can be constructed with `CopilotResponse`, it is always set as `null` in current code base (which also caused the `TopicName` not collected in the Telemetry). As we need user consent to save the IDs and we are not asking for user consent when an error occurs, I think it should be good to just remove the response parameter.
- Make the EventType clearer to easier identify AIShell Exceptions from all exceptions logged, which would make query easier. Because we are sharing 1 app inisghts resource between AIShell and AzPS/ AzCLI Endpoint. (Please feel free to raise any other suggestions, for example shall we create a new column for this? Like {EventType: "Exceprion", ExceptionFrom: "AIShell"}.)

Remove id for correlation from Exception.

---

shell/agents/Microsoft.Azure.Agent/ChatSession.cs

Fix a bug to only report unexpected errors in `SetupNewChat`.
The `TokenRequestException` error will be reported before throwing the exception, so we shouldn't report it again.

Fix a bug to only report unexpected errors in `SetupNewChat`

---

shell/agents/Microsoft.Azure.Agent/ChatSession.cs
shell/agents/Microsoft.Azure.Agent/DataRetriever.cs

- Make the dynamic argument value retrieval cross-platform
- Update the authentication status messages to not show the `DirectLine` token request.

Make the dynamic argument value retrieval cross-platform

---

shell/AIShell.Integration/AIShell.psd1
shell/AIShell.Kernel/Command/CodeCommand.cs
shell/AIShell.Kernel/Command/CommandRunner.cs
shell/AIShell.Kernel/Command/RenderCommand.cs
shell/AIShell.Kernel/Utility/ReadLineHelper.cs
shell/AIShell.Kernel/Utility/Utils.cs

- Improve the path completion and tilde support in path
- Make path completion better handle quotes and spaces in the path
- Make path completion able to work for paths starting with `~`
- Add support for tilde expansion in the path for `/code save <file-path>`
- Update the minimal PowerShell version required for loading the `AIShell` module
- Comment out the `/render` command, which is for debugging purposes.

Improve the path completion and tilde support in path

---

shell/agents/Microsoft.Azure.Agent/ChatSession.cs

Update status message to be more user friendly -- not call out "access token" and "DirectLine token", which uses won't know anything about and don't care.

Update status message to be more user friendly

---

shell/agents/Microsoft.Azure.Agent/AzureAgent.cs

Update an error message to make it look better.
Before change:
After change:

Update an error message

---

shell/AIShell.Abstraction/IShell.cs
shell/AIShell.Kernel/Shell.cs
shell/agents/Microsoft.Azure.Agent/AzureAgent.cs
shell/agents/Microsoft.Azure.Agent/Command.cs
shell/shell.common.props

- Update `IShell` to expose whether a channel to a shell application has been established.
- Add suggestion to use `/code post` or `/code copy` after parameter injection (placeholder replacement), depending on whether a connected shell is available.
When no channel is available:
When channel is available:

Add suggestion to use `/code post` or `/code copy` after parameter injection

---

shell/agents/Microsoft.Azure.Agent/Telemetry.cs

- Updated the telemetry functionality by adding information about the operating system platform. 
- Extracted `GetInstallationId()` and `GetOSPlatform()` to make the `initialize()` more readable. 
- TODO: Update the connect string for app insights. Will do tomorrow when I get my SAW on hand to access AME env.

Add OS Platform Infromation in Telemetry

---

shell/agents/Microsoft.Azure.Agent/AzureAgent.cs

The response from Azure Copilot occasionally uses the Bash line-continuation operator in the generated commands even for a Windows user. The line continuation separated code blocks cause the current parsing logic for parameter injection to fail, and it would be too risky to fix now especially considering such responses don't happen often (only 1 report on this so far).
I think a better solution is to update instruction to ask GTP to not use line continuation operator in generated commands. This should make it much less possible for a customer to run into this issue.

Update instruction to not use line continuation operator in generated commands

---

shell/agents/Microsoft.Azure.Agent/Command.cs

Update the error message when `/replace` cannot do its work.

Update the error message when `/replace` cannot do its work

---

shell/agents/Microsoft.Azure.Agent/AzureAgent.cs

Fix #290
I cannot reproduce the issue locally, but by looking at the code based on the error messages in the screenshot, I believe it was because the error response from Azure Copilot did not contain `ConversationState` when the problem happened. So, I'm adding a check to update `_turnsLeft` only if `ConversationState` is not null.
I also added a telemetry when receiving error response from Azure Copilot.
It's easier to review by ignoring all whitespace changes: https://github.com/PowerShell/ProjectMercury/pull/291/files?w=1

Fix a null-ref exception and add telemetry for error response from Az Copilot

---

build.psm1
shell/AIShell.Integration/AIShell.psd1
tools/metadata.json

Merge the release branch for v1.0.0-preview.1 release into the main branch.

Merge the release branch for v1.0.0-preview.1 release into the main branch

---

shell/agents/Microsoft.Azure.Agent/ChatSession.cs
shell/agents/Microsoft.Azure.Agent/Command.cs
shell/agents/Microsoft.Azure.Agent/Schema.cs

We got report that AI Shell cannot create a chat session in France with the following failure:
```
ERROR: Failed to open an conversation. HTTP status: Forbidden, Response: {
"error": {
"code": "RegionNotAllowed",
"message": "The request received in france but target regional bot belongs to europe. Please check BaseURI
https://docs.microsoft.com/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-api-reference?view=azure-bot-se
rvice-4.0#base-uri."
}
}
```
It turns out we need to use different Direct Line base URL for different regions. To handle that, we should use the base URL returned from the 'start-conversation' API instead of hardcoding it.

Use the DirectLine base URL returned from the 'start-conversation' API

---

shell/AIShell.Kernel/Command/AgentCommand.cs

On Linux, we actually cannot depend on `shell execute` to open a file in its default editor, especially if the Linux is headless (e.g. WSL). This PR changes it to use `nano` or `$EDITOR` (if defined) to open the config file on Linux.

Use `nano` or `$EDITOR` (if defined) to open the config file on Linux

---

shell/agents/AIShell.OpenAI.Agent/AIShell.OpenAI.Agent.csproj
shell/agents/AIShell.OpenAI.Agent/Agent.cs
shell/agents/AIShell.OpenAI.Agent/Helpers.cs
shell/agents/AIShell.OpenAI.Agent/ModelInfo.cs
shell/agents/AIShell.OpenAI.Agent/Service.cs

- Move to `Azure.AI.OpenAI` v2.1.0 and refactor the `openai-gpt` agent to accommodate the breaking changes in the new version.
- Also move from `SharpToken` to `Microsoft.ML.Tokenizers`, as the latter becomes the official one for the .NET ecosystem.
- Change to use the `usage` report from AI to track the tokens used for our chat history instead of trying to count the tokens ourselves, because it's almost impossible to relative-accurately calculate the token counts of all messages, especially when tool calls are involved (tool call definitions and the tool call payloads in AI response).

Refactoring work to move to Azure.AI.OpenAI v2.1.0

---

shell/agents/Microsoft.Azure.Agent/AzureAgent.cs
shell/agents/Microsoft.Azure.Agent/ChatSession.cs
shell/agents/Microsoft.Azure.Agent/Schema.cs

Add azure powershell credential

---

shell/agents/AIShell.OpenAI.Agent/GPT.cs
shell/agents/AIShell.OpenAI.Agent/ModelInfo.cs
shell/agents/AIShell.OpenAI.Agent/Service.cs

Add support for users to user an AI endpoint whose API is compatible with OpenAI API format.
1. **Azure OpenAI**
It requires the `endpoint`, `deployment name`, and the `model name`.
2. **Public OpenAI**
It requires the `model name`. No endpoint, no deployment name.
3. **OpenAI-compatible AI endpoint**
It requires the `endpoint` and `model name`. No `deployment name`.
`CompatibleThirdParty` is added as a new `EndpointType` member.
Many LLM tools can setup local or remote API endpoint that is compatible with OpenAI API format for users to call a model hosted by the tool, such as [Ollama](https://ollama.com/blog/openai-compatibility), [LM Studio](https://lmstudio.ai/docs/api/openai-api), [LocalAI](https://localai.io/). The [DeepSeek v3](https://api-docs.deepseek.com/) and [Google …

Allow using 3rd party AI services that are compatible with OpenAI API format in the `openai-gpt` agent

---

shell/agents/AIShell.OpenAI.Agent/Agent.cs

Fix #327
Check for update before return the description, so that `/refresh` command can get the up-to-date description from the `openai-gpt` agent.

Check for update before return the description for the `openai-gpt` agent

---

shell/AIShell.Kernel/Host.cs
shell/AIShell.Kernel/Shell.cs

Fix #322
Use `#7a7a7a` as the grey color in AIShell, which seemed to be the most similar to what we already have but high enough contrast to pass the contrast checker.

Use `#7a7a7a` as the grey color in AIShell to meet the contrast requirement

---

shell/agents/Microsoft.Azure.Agent/ChatSession.cs

According to our telemetry data, we are no longer seeing any fallback to canary for Copilot authorization check. This indicates the fix has been deployed on the Azure Copilot side and we don't need the fallback anymore.
Remove the fallback logic for authorization check and stick to the production URL.

Remove the fallback logic for authorization check and stick to the production URL

---

shell/AIShell.Integration/Commands/ResolveErrorCommand.cs

Update the `Resolve-Error` command to capture native command output using screen scraping API on Windows.
On non-Windows or when screen scraping fails with exception, we fall back to the existing `UseClipboardForCommandOutput` approach for the native command output.

Capture native command output using screen scraping API on Windows

---

shell/agents/Microsoft.Azure.Agent/ChatSession.cs
shell/agents/Microsoft.Azure.Agent/Schema.cs

The required fixes to the `pluginstore` feature of Azure Copilot have been deployed, so we are enabling the `pluginstore` feature when talking to Azure Copilot and update the topic name for CLI handler (it uses `generate_azure_cli_scripts` as the topic name now).

Enable the `pluginstore` feature when talking to Azure Copilot and update the topic name for CLI handler

---

shell/agents/Microsoft.Azure.Agent/AzureAgent.cs

When an exception is thrown while processing a user query, we log the exception and the response text if it's available.
This can help us diagnose the exception. The response text is logged to the local log, not sent to the telemetry, so there is no privacy issue.
This PR also reset `_copilotResponse` and the placeholder data when `/refresh` or when the user sends a new query, so that old data doesn't interfere when user runs `/replace` after `/refresh`, or when user runs `/replace` after it fails to get a response from Azure Copilot.

Log the response text if available when exception is thrown while processing a user query

---

build.psm1
shell/AIShell.App/AIShell.App.csproj
shell/AIShell.Kernel/Utility/LoadContext.cs
shell/agents/Microsoft.Azure.Agent/AzureAgent.cs
shell/agents/Microsoft.Azure.Agent/Command.cs
shell/agents/Microsoft.Azure.Agent/DataRetriever.cs
shell/agents/Microsoft.Azure.Agent/Microsoft.Azure.Agent.csproj
shell/agents/Microsoft.Azure.Agent/Schema.cs
shell/agents/Microsoft.Azure.Agent/Utils.cs

This PR enables parameter injection for responses from the Azure PowerShell handler.
- Supporting parameter injection for Azure PowerShell response requires to have PowerShell runtime available. However, pulling PowerShell dependencies at the agent level doesn't work because an agent gets loaded to its own `AssemblyLoadContext`, while PowerShell runtime has to live in the default `AssemblyLoadContext`. The solution is to make `AIShell` depend on PowerShell SDK so that the PowerShell dependencies are moved to the application level and are loaded into the default `AssemblyLoadContext`. With that, any agent can use PowerShell without needing to pull PowerShell dependency assemblies into the agent's folder.
- Updated the build script to properly deploy the PowerShell modules. They need to be …

Enable parameter injection for Azure PowerShell response

---

tools/packaging/packaging.psm1
tools/scripts/install-aishell.ps1

- Make packaging throw on Linux/macOS when the command `chmod` cannot be found
- Update `install-aishell.ps1` to allow user to specify version to install. When version is not specified, the latest release will be installed.

Update `install-aishell.ps1` to allow user to specify version to install

---

shell/agents/Microsoft.Azure.Agent/AzureAgent.cs
shell/agents/Microsoft.Azure.Agent/ChatSession.cs
shell/agents/Microsoft.Azure.Agent/DataRetriever.cs
shell/agents/Microsoft.Azure.Agent/Schema.cs

Update flight flags and make corresponding changes:
1. Add the flag `pipelineorchestration` per the Azure Copilot team's request.
2. Update flag values based on the values used by Azure Portal, and remove 2 flags that are no longer used by Azure Portal.
3. Update the topic names for AzCLI handler and AzPS handler. They changed after adopting the new flag values.
4. Simplify the instruction prompt to save words for the input. Also include Azure PowerShell in the instruction.
5. Use better OS description for the instruction prompt.
6. Log the topic name for every response, for diagnostic purpose. We already send this information in telemetry.
7. Fix a bug in response parsing in the validation of the beginning of placeholder section.
8. Fix the status report to only report `ProgressTopic` …

Update flight flags and make corresponding changes

---

shell/Markdown.VT/ColorCode.VT/Parser/Bash.cs
shell/Markdown.VT/ColorCode.VT/Parser/PowerShell.cs

1. Fix the single-quote string regex for PowerShell -- backslash `\` is allowed at any position in a single-quoted string
2. Simplify the regex for double-quoted string regex for PowerShell -- the single-line mode `(?s)` has no effect because `.` is not used.
3. Add single-quote string and double-quote string regexes to Bash.

Update the regex for matching single-quote and double-quote strings for PowerShell and Bash

---

shell/agents/AIShell.Interpreter.Agent/AIShell.Interpreter.Agent.csproj
shell/agents/AIShell.Interpreter.Agent/Agent.cs
shell/agents/AIShell.Interpreter.Agent/Service.cs
shell/agents/AIShell.Interpreter.Agent/Settings.cs
shell/agents/AIShell.OpenAI.Agent/AIShell.OpenAI.Agent.csproj
shell/agents/AIShell.OpenAI.Agent/Agent.cs
shell/agents/AIShell.OpenAI.Agent/GPT.cs
shell/agents/AIShell.OpenAI.Agent/Service.cs
shell/agents/AIShell.OpenAI.Agent/Settings.cs

Adds support for Entra ID authentication by specifying AuthType: "EntraID". This enables users to use "AuthType": "EntraID" instead of specifying an API key
Many organizations have a blanket ban on API keys, so this allows people in such situations to use AIShell.

Add support for Entra ID authentication when using interpreter or openai-gpt

---

shell/AIShell.Integration/AIShell.psd1
shell/agents/AIShell.OpenAI.Agent/GPT.cs
shell/shell.common.props
tools/metadata.json

Merge the 1.0.0-preview.3 release branch back to main.
- Minor coding style changes to the `GPT.cs` in `openai-gpt` agent
- Update version info for `1.0.0-preview.3` release

Merge the 1.0.0-preview.3 release branch back to main

---

shell/AIShell.Integration/AIShell.psd1
shell/AIShell.Integration/AIShell.psm1
shell/AIShell.Integration/Channel.cs
shell/AIShell.Integration/Commands/InvokeAishCommand.cs

By leveraging the fix in https://github.com/PowerShell/PSReadLine/pull/4442, which handles buffer changes made by a handler of the `OnIdle` event, now we are able to post code to PowerShell from the sidecar AIShell even when PowerShell is busy running a command. The posted code will be inserted into prompt after PowerShell finishes running the current command.
- Add `-PostCode`, `-CopyCode`, and `-Exit` parameters to `Invoke-AIShell` in their separate parameter sets. So, a user don't have to leave the PowerShell session they are working in -- they can send query, copy or post code from the AI response, and exit the sidecar AIShell directly from the PowerShell session.
- When the `CodePost` message comes in, the `AIShell` module will check if `PSReadLine` is active (whether PSReadLine is …

Support posting code from the sidecar AIShell to PowerShell with `Invoke-AIShell -PostCode`

---

shell/AIShell.Integration/AIShell.psd1
shell/AIShell.Integration/Channel.cs
shell/AIShell.Integration/Commands/StartAishCommand.cs
shell/AIShell.Integration/InitAndCleanup.cs

This PR significantly improves the reliability of `Start-AIShell` on macOS, by the following changes:
1. Create an Python virtual environment for installing `iterm2` package. We cannot install `iterm2` system-wide because for Python 3.11 or higher versions, it's not allowed to install package system-wide with `pip` by default -- you will get the "external-managed-environment" error.
1. The "creating a virtual environment" work is slow and thus pushed to a background thread as soon as the `InitAndCleanup` type initializes.
1. Make `pypi.org` and `files.pythonhosted.org` as trusted hosts, because a security software may cause issue to SSL validation for access to/from those two endpoints, and thus prevents package installation.
1. Save the python script for splitting the iterm2 tab in …

Improve the reliability of `Start-AIShell` on macOS

---

.pipelines/Package-Official.yml
.pipelines/Release-Official.yml
.pipelines/templates/module-package.yml
.pipelines/templates/nupkg-package.yml
.pipelines/templates/release-publish-github.yml
.pipelines/templates/release-publish-module.yml
.pipelines/templates/release-publish-nuget.yml

Use deploy box to publish artifacts to nuget.org and powershellgallery.com.
1. Use `KS3` in all places.
2. Expose the parameter 'publish' for the release pipeline, so we can control if we really want to publish artifacts for the release.
3. Use deploy box to publish artifacts to nuget.org and powershellgallery.com
The pipeline runs to verify the changes:
Building: https://dev.azure.com/mscodehub/PowerShellCore/_build/results?buildId=581933&view=results
Packaging: https://dev.azure.com/mscodehub/PowerShellCore/_build/results?buildId=581955&view=results
Releasing: https://dev.azure.com/mscodehub/PowerShellCore/_build/results?buildId=581967&view=results

Publish artifacts in deploy box

---

shell/AIShell.Integration/AIShell.psm1
shell/AIShell.Integration/Channel.cs

Fix #172
This PR fixes the following scenarios on macOS
1. Running `/code post` from the `AIShell` pane to post code to the `PowerShell` pane
2. Running `Invoke-AIShell -PostCode` from the `PowerShell` to request code to be posted from the `AIShell` pane.
**[NOTE]** Now the `AIShell` module depends on the **v2.4.2-beta2** PSReadLine, because a private field was added in PSReadLine to accurately indicate if PSReadLine is initialized and ready to render (https://github.com/PowerShell/PSReadLine/pull/4706).
The `AIShell` module starts to depend on that field to be more deterministic about if PSReadLine is running and ready. Before this change, we relied on `Console.TreatControlCAsInput` which is not accurate and may cause race condition: `Console.TreatControlCAsInput` is set to true, but …

Fix code posting on macOS

---

shell/agents/AIShell.OpenAI.Agent/ModelInfo.cs
shell/agents/AIShell.OpenAI.Agent/Service.cs

Fix #360
Update model information to support the new OpenAI models.
- The OpenAI reasoning models do not support the `temperature` setting -- they error out if you set the value. But the `DeepSeek R1` OpenAI compatible API still allows passing the `temperature` setting even though it has not effect.
- I don't have access to the `o3` model (requires verifying organization), but I've verified the changes with `o1`, `o3-mini`, `o4-mini`, `gpt-4.1`, `gpt-4.1-mini`, and `gpt-4.1-nano` modules and it works fine.
- The `o1-mini` model doesn't work because it doesn't support the system prompt (very weird). Given that the `o3-mini` is out and recommended, I think it's fine to not work with `o1-mini`.
Regarding the reasoning/thinking tokens:
- The OpenAI reasoning models do not expose the Chain of …

Update model information to support the new OpenAI models

---

shell/AIShell.Kernel/Command/ClearCommand.cs
shell/AIShell.Kernel/Command/CommandRunner.cs
shell/AIShell.Kernel/Command/HelpCommand.cs

Add `/clear` as an alias to `/cls`. Fix #315

Add `/clear` as an alias to `/cls`

---

shell/AIShell.Integration/AIShell.psm1
tools/scripts/install-aishell.ps1

Since the integration experience is mostly fixed on macOS, we should install `AIShell` module on macOS too.
- Update the `AIShell` module to check if it's running in iTerm2, and throw if not
- Update the installation script to install `AIShell` module on macOS
- Update the messages in installation script accordingly

Update installation script to install `AIShell` module on macOS too

---

build.psm1
shell/agents/AIShell.PhiSilica.Agent/AIShell.PhiSilica.Agent.csproj
shell/agents/AIShell.PhiSilica.Agent/PhiSilicaAgent.cs

This is implementation of an agent for PhiSilica or Copilot+ PCs. This enables AI shell to be used in offline scenarios using the onboard SLM Phi Silica on Copilot+PCs.

Adding Phi Silica Agent for Copilot+PCs

---

.pipelines/Release-Official.yml
.pipelines/templates/linux-package.yml
.pipelines/templates/mac-package.yml
.pipelines/templates/module-package.yml
.pipelines/templates/release-publish-github.yml
.pipelines/templates/windows-package.yml
shell/AIShell.Integration/AIShell.psm1
shell/AIShell.Integration/Channel.cs
shell/shell.common.props
tools/metadata.json

Merge the 1.0.0-preview.4 release branch back to main.
- Update version info for the `1.0.0-preview.4` release.
- Use deploy box and `GitHubRelease` task to create the GitHub draft release.
- Make sure the `Runspace` is available when importing the `AIShell` module and throw otherwise.
- When validating packages, I found there were rare cases where the `Runspace` instance passed to the constructor of `AIShell.Integration.Channel` is `null`. The constructor is used only in the public static method `CreateSingleton` which is called from `AIShell.psm1` to create a singleton of the `Channel` type upon importing the `AIShell` module.
- In `AIShell.psm1`, we call `CreateSingleton` with `$host.Runspace` to pass in the `Runspace` instance, and the module's manifest defines `PowerShellHostName = …

Merge the 1.0.0-preview.4 release branch back to main

---

tools/scripts/install-aishell.ps1

Starting from 1.0.0-preview.4 of AIShell release, the AIShell module depends on PSReadLine 2.4.2-beta2 or higher version.
This PR updates the install script to install the PSReadLine dependency if the required version of PSReadLine is missing.

Update the install script to install the PSReadLine dependency as needed

---

shell/agents/AIShell.OpenAI.Agent/Service.cs

The `InteractiveBrowserCredential` is excluded by default because it requires user's interaction.
Update `DefaultAzureCredential` to allow `InteractiveBrowserCredential`.
We got report that when using Entra id login, it doesn't fall back to the `InteractiveBrowserCredential`.
```
ERROR: Agent failed to generate a response: DefaultAzureCredential failed to retrieve a token from the included credentials. See the troubleshooting guide for more information.
https://aka.ms/azsdk/net/identity/defaultazurecredential/troubleshoot
- EnvironmentCredential authentication unavailable. Environment variables are not fully configured. See the troubleshooting guide for more information.
https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot
- WorkloadIdentityCredential authentication …
```

Update `DefaultAzureCredential` to allow `InteractiveBrowserCredential`

---

shell/AIShell.Abstraction/NamedPipe.cs
shell/AIShell.Integration/AIShell.psm1
shell/AIShell.Integration/Channel.cs
shell/AIShell.Integration/Commands/InvokeAishCommand.cs
shell/AIShell.Kernel/Command/CodeCommand.cs
shell/AIShell.Kernel/Command/McpCommand.cs
shell/AIShell.Kernel/Host.cs
shell/AIShell.Kernel/MCP/BuiltInTool.cs
shell/AIShell.Kernel/MCP/McpConfig.cs
shell/AIShell.Kernel/MCP/McpManager.cs
shell/AIShell.Kernel/MCP/McpTool.cs

This PR exposes built-in tools to agents of AIShell. The built-in tools are also exposed as `AIFunction` instances so they can be consumed similarly as the MCP client tools.
The detailed changes are:
1. Updated the channel between the `AIShell` module and `aish` app to support retrieving context information from the connected PowerShell session. The supported context information includes:
- `CurrentLocation` 
- `CommandHistory` 
- `TerminalContent`
- `EnvironmentVariables`
2. Updated the `AIShell` module to
- keep track of the "current location" and "command history" using `Runspace.AvailabilityChanged` and `InvokeCommand.LocationChangedAction` events.
- support retrieving terminal window content on Windows using screen scraping.
- support get environment variables and their values (value …

Add built-in tools to AIShell

---

shell/AIShell.Abstraction/NamedPipe.cs
shell/AIShell.Integration/AIShell.psd1
shell/AIShell.Integration/Channel.cs
shell/AIShell.Integration/Commands/InvokeAiCommand.cs
shell/AIShell.Integration/RunInTerminal.cs
shell/AIShell.Kernel/Command/CodeCommand.cs
shell/AIShell.Kernel/Host.cs
shell/AIShell.Kernel/MCP/BuiltInTool.cs
shell/AIShell.Kernel/MCP/McpTool.cs
shell/AIShell.Kernel/ShellIntegration/Channel.cs
shell/agents/AIShell.OpenAI.Agent/Helpers.cs

Allow AIShell to run command in the connected PowerShell session and collect all output and error.
1. Add `Invoke-AICommand` cmdlet (alias: `airun`) to `AIShell` module. Commands sent from the sidecar AIShell will be executed through this command in the form of `airun { <command> }`. This command is designed to collect all output and error messages as they are displayed in the terminal, while preserving the streaming behavior as expected.
2. Add `RunCommand` and `PostResult` messages to the protocol.
3. Update the `Channel` class in `AIShell` module to support the `OnRunCommand` action. We already support posting command to the PowerShell's prompt, but it turns out not easy to make the command be accepted. On Windows, we have to call `AcceptLine` within an `OnIdle` event handler and it …

Add the built-in tool `run_command_in_terminal` for AI to execute commands in the connected PowerShell session

---

shell/AIShell.Integration/AIShell.psd1
shell/AIShell.Integration/AIShell.psm1
shell/AIShell.Kernel/MCP/BuiltInTool.cs
shell/shell.common.props
tools/metadata.json
tools/scripts/install-aishell.ps1

- Increment the versions for AIShell application and the AIShell module.
- Update the check in AIShell module to look for PSReadLine v2.4.3-beta3 and above.
- Hide the `run_command_in_terminal` tool in macOS.
- Update the installation script to find the right PSReadLine dependency for a particular version of AIShell module.

Merge the 1.0.0-preview.6 release branch back to main

---

shell/agents/Microsoft.Azure.Agent/Microsoft.Azure.Agent.csproj
shell/agents/Microsoft.Azure.Agent/Telemetry.cs

Fix #393
I can reproduce this issue on macOS with the error from `AzurePowerShellCredential()` being `"PowerShell did not return a valid response."` This turns out to be an issue with the `Azure.Identity` library (https://github.com/Azure/azure-sdk-for-net/issues/50578). After moving to the latest `1.14.2` of the package, it works for me on macOS.
----
However, moving to the `1.14.2` of the `Azure.Identity` caused a dependency conflict with the `Microsoft.ApplicationInsights.WorkerService` package, which brings in an older version of `Microsoft.Extensions.DependencyInjection` that conflicts with the newer version of `Microsoft.Extensions.DependencyInjection.Abstractions` that comes with `Azure.Identity`.
In fact, we should not depend on `Microsoft.ApplicationInsights.WorkerService`, but …

Move to 'Azure.Identity' v1.14.2 and refactor the telemetry library

---

shell/AIShell.Integration/InitAndCleanup.cs

On macOS, when using the sidecar experience, `aish` cannot start local MCP servers and the `Azure` agent cannot get the access token from Az CLI.
This is due to the PATH environment variable not properly setup when iTerm2 starts `"aish --Channel ..."` in the new pane. iTerm2 uses `exec` to run the `aish` command, which directly execute the program without setting up the environment variables properly.
Because of that, the `az` and `pwsh` commands cannot be found when retrieving access token, and the MCP server commands cannot be found too, which caused local MCP servers to always fail to start.
The fix is to wrap it with `zsh` by `/bin/zsh -l -c "<aish-path> --channel <channel-string>"`. In this way, `zsh` will set up the environment properly, which will then be inherited by `aish`.
----- …

Use login shell to start `aish` in sidecar pane to inherit proper environment PATH

---

shell/AIShell.Kernel/Host.cs

Tool description may contain characters like `"[]"`, which will result in malformed `Markup` object because the square brackets characters have special meaning in markup language.
The `set_config_value` tool from the MCP server `desktop-commander` is an example of this bug -- it has `"empty array ([])"` in its description.
The fix is to escape tool description to avoid malformed 'Markup' object.

Properly escape tool description to avoid malformed 'Markup' object

---

shell/AIShell.Kernel/Shell.cs
shell/agents/AIShell.OpenAI.Agent/GPT.cs

Fix https://github.com/PowerShell/AIShell/issues/410
This PR contains the following 2 fixes:
1. Keep the original casing of the model's name for custom endpoint configuration.
2. Fix the error reporting to handle exception messages that already contains newline at the end.
OpenAI models require lower case for their names, but the custom endpoint may be case-sensitive, such as the endpoint set up by Foundry Local. So, we should keep the original casing for custom endpoint configurations.
1. Update the `openai.agent.json` file with the following GPT configuration:
```json
{
"GPTs": [
{
"Name": "foundry-local",
"Description": "A GPT instance using Foundry Local.",
"Endpoint": "http://127.0.0.1:56952/v1",
"ModelName": "Phi-3.5-mini-instruct-generic-cpu",
"Key": "OPENAI_API_KEY"
}
]
"Active": …
```

Keep the original casing of model name for custom endpoint to enable Foundry Local
